project:
  type: website

website:
  title: "colabe.info"
  description: colaboratório de informação 
  site-url: https://colabe.info
  navbar:
    left:
      - sobre.qmd
    tools:
      - icon: github
        href: https://github.com/jultty
      - icon: linkedin
        href: https://linkedin.com/in/jultty
      - icon: envelope
        href: mailto:juno@newen.me
  favicon: assets/favicon.svg
  open-graph: true
  repo-url: https://github.com/jultty/colabe
  repo-actions: source
  reader-mode: false
  page-footer:
    center:
      - icon: rss
        href: /index.xml

format:
  html:
    theme: 
      light: litera
      dark: solar
    css: styles.css
    toc: true

execute:
  freeze: auto
